services:
  backend:
    build: ./backend
    container_name: ngocnguyen_backend
    image: ngocnguyen_flask_backend
    volumes:
      - ./logs:/logs
    ports:
      - "5000:5000"
    environment:
      - LOG_PATH=/logs
      
  frontend:
    image: nginx:latest
    container_name: ngocnguyen_frontend
    ports:
    - "8089:80"
    volumes:
    - ./frontend:/usr/share/nginx/html:ro
    - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
    - backend